# Generated by Django 2.2.15 on 2020-08-14 17:52

from django.db import migrations, models
import domains.models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_auto_20200814_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[domains.models.validate_case_sentitivity]),
        ),
    ]
