# Generated by Django 2.2.15 on 2020-08-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('domains', '0004_auto_20200814_2322'),
        ('domain_feature_mapping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domainfeaturemapping',
            old_name='domain_id',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='domainfeaturemapping',
            old_name='feature_id',
            new_name='feature',
        ),
        migrations.AlterUniqueTogether(
            name='domainfeaturemapping',
            unique_together={('domain', 'feature')},
        ),
    ]
