# Generated by Django 2.2.15 on 2020-08-16 20:00

from django.db import migrations, models
import features.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, validators=[features.models.validate_case_sentitivity])),
            ],
        ),
    ]
